#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Production values are kept apart from the local development .env, which has
# defaults for a throwaway Postgres and should never hold a Supabase credential.
ENV_FILE=".env.production"

banner "Platform deployment setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase: create the project"
say "The Platform's database is Supabase Cloud (ADR-0002). This stage creates"
say "the project and captures the connection string the API will use."
open_url "https://supabase.com/dashboard/new"
step "Create a new project. Pick the region closest to the plant, not to you:"
say "  every query the API makes pays that round trip."
step "Choose a strong database password and save it in your password manager."
say "  Supabase shows it once."
step "Wait for the project to finish provisioning (a minute or two)."
pause "Project created and provisioned?"

step "Now open Project Settings -> Database, and find the connection string."
say "Choose the SESSION POOLER string, not the direct connection."
say "The direct one resolves over IPv6 only unless you buy the IPv4 add-on,"
say "and your LXC will most likely reach it over IPv4."
step "Replace [YOUR-PASSWORD] in the string with the password you just saved."
ask_secret DATABASE_URL "Paste the session pooler connection string:"
write_env DATABASE_URL "$DATABASE_URL"
# The deploy passes this to the API. It is also what migrations will run
# against once the schema baseline lands.
set_secret DATABASE_URL "$DATABASE_URL"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Supabase: API keys"
say "Three values from one page. The API needs the service role key; the"
say "Flutter app needs the URL and the anon key, which ship to the browser."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Copy the Project URL (looks like https://<ref>.supabase.co)."
ask SUPABASE_URL "Paste the project URL:"
step "Copy the anon / public key. Newer projects may label this 'publishable'."
ask SUPABASE_ANON_KEY "Paste the anon key:"
step "Reveal and copy the service_role key. Newer projects label this 'secret'."
say "This key bypasses Row Level Security entirely. It belongs only to the API,"
say "and must never reach the Flutter bundle."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service role key:"

write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
# The anon key is meant to be public: it is shipped to every browser. That is
# precisely why the database is a deny-all floor (ADR-0004), and why this one
# is a variable rather than a secret.
set_var SUPABASE_URL "$SUPABASE_URL"
set_var SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
set_secret SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Hostname, DNS and port forwarding"
say "The Platform is served from one hostname: /api goes to the API and"
say "everything else to the Flutter app, so the browser sees a single origin"
say "and there is no CORS anywhere."
ask APP_HOSTNAME "Hostname for the Platform (e.g. platform.example.com):"
ask ACME_EMAIL "Email for Let's Encrypt expiry notices:"
ask LXC_HOST "IP or hostname of the LXC on your network (e.g. 192.168.1.60):"

step "In your DNS provider, add an A record for $APP_HOSTNAME pointing at your"
say "  PUBLIC IP address (not the LXC's private address)."
step "On your router, forward TCP ports 80 and 443 to $LXC_HOST."
say "Port 80 is not optional: Let's Encrypt uses it to prove you own the name."
pause "DNS record added and ports forwarded?"

say "Checking that the name resolves..."
if command -v dig >/dev/null 2>&1; then
  dig +short "$APP_HOSTNAME" | sed 's/^/    /' || true
elif command -v nslookup >/dev/null 2>&1; then
  nslookup "$APP_HOSTNAME" 2>/dev/null | tail -4 | sed 's/^/    /' || true
else
  note "no dig or nslookup here; check the record yourself before continuing"
fi
say "If nothing appeared above, DNS has not propagated yet. Certificates will"
say "fail until it has, so it is worth waiting here rather than pressing on."
pause "Does that look right?"

write_env APP_HOSTNAME "$APP_HOSTNAME"
write_env ACME_EMAIL "$ACME_EMAIL"
write_env LXC_HOST "$LXC_HOST"
set_var APP_HOSTNAME "$APP_HOSTNAME"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "LXC: Docker Engine and the compose plugin"
say "Everything on the box runs as containers, so this is the only software"
say "the LXC needs installed directly."
step "Open a shell on the LXC:"
say "    ssh <you>@$LXC_HOST"
step "Install Docker Engine and the compose plugin:"
say "    curl -fsSL https://get.docker.com | sudo sh"
step "Let your user run docker without sudo, then reconnect so it takes effect:"
say "    sudo usermod -aG docker \$USER && exit"
step "Reconnect and confirm both are present:"
say "    docker --version && docker compose version"
step "Create the directory the Platform will run from, and the network its"
say "  containers share with the proxy:"
say "    sudo mkdir -p /opt/lean-platform && sudo chown \$USER /opt/lean-platform"
say "    docker network create platform"
pause "Docker installed, directory and network created?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "LXC: sign in to GHCR"
say "The images are private, so the LXC needs credentials to pull them."
say "Workflows use the built-in token, but pulling by hand needs your own."
open_url "https://github.com/settings/tokens/new?scopes=read:packages&description=lean-platform%20LXC%20pull"
step "Generate the token. read:packages is the only scope it needs — this token"
say "  lives on a box, so give it nothing it does not require."
step "Copy the token, then on the LXC run:"
say "    docker login ghcr.io -u phamtruonghung"
step "Paste the token when it asks for a password."
say "The wizard deliberately does not capture this value: it is typed straight"
say "into the box that uses it and stored nowhere else."
pause "Signed in to GHCR from the LXC?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "LXC: the reverse proxy, with staging certificates"
say "Caddy terminates TLS and splits the hostname: /api to the API, the rest"
say "to the Flutter app. It obtains and renews certificates by itself."
say ""
say "Start on the Let's Encrypt STAGING service. Production allows only 5"
say "failures per hostname per hour, and a wrong DNS record or an unforwarded"
say "port will burn through that and lock you out. Browsers warn about staging"
say "certificates until the last stage switches over."

if [[ ! -f deploy/Caddyfile ]]; then
  warn "deploy/Caddyfile not found — run this wizard from the repository root"
  exit 1
fi

step "Copy the proxy configuration to the LXC:"
say "    scp deploy/Caddyfile deploy/caddy.compose.yml <you>@$LXC_HOST:/opt/lean-platform/"
step "On the LXC, switch it to staging by UNCOMMENTING the acme_ca line near"
say "  the top of /opt/lean-platform/Caddyfile:"
say "    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory"
step "Start the proxy:"
say "    cd /opt/lean-platform"
say "    COMPOSE_PROJECT_NAME=platform-edge \\"
say "      APP_HOSTNAME=$APP_HOSTNAME ACME_EMAIL=$ACME_EMAIL \\"
say "      docker compose -f caddy.compose.yml up -d"
say "The project name matters: application deploys remove any container in THEIR"
say "project that they do not define, so sharing a name would delete the proxy."
step "Watch it request a certificate:"
say "    docker logs -f platform-caddy"
say "Nothing is behind the proxy yet, so a 502 from outside is the correct answer"
say "at this point. What matters is that a certificate was issued."
pause "Certificate issued (from the staging service)?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "LXC: register the self-hosted Actions runner"
say "The runner polls GitHub outbound and runs the deploy on the box, so"
say "nothing inbound is exposed and no SSH key is stored in GitHub."
open_url "https://github.com/PhamTruongHung/lean-platform/settings/actions/runners/new?arch=x64&os=linux"
step "That page shows a download-and-configure script with a registration"
say "  token in it. Run those commands on the LXC, in a directory of its own:"
say "    mkdir -p ~/actions-runner && cd ~/actions-runner"
step "When ./config.sh asks for labels, add:  lean-platform"
say "The deploy workflow targets that label, so a runner without it is never"
say "chosen and deploys will queue forever with no obvious reason."
step "Install it as a service so it survives a reboot:"
say "    sudo ./svc.sh install && sudo ./svc.sh start"
step "Confirm the runner shows as Idle on the page above."
pause "Runner registered, labelled and idle?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Switch to production certificates"
say "The hostname resolves, the ports are forwarded, and staging proved the"
say "whole path works. Now swap in real certificates."
step "On the LXC, comment the acme_ca line back out in"
say "  /opt/lean-platform/Caddyfile, returning it to how the repository ships it:"
say "    #acme_ca https://acme-staging-v02.api.letsencrypt.org/directory"
step "Restart the proxy so it requests from the production service:"
say "    cd /opt/lean-platform"
say "    COMPOSE_PROJECT_NAME=platform-edge \\"
say "      APP_HOSTNAME=$APP_HOSTNAME ACME_EMAIL=$ACME_EMAIL \\"
say "      docker compose -f caddy.compose.yml restart"
step "Confirm the certificate is trusted:"
say "    curl -I https://$APP_HOSTNAME"
say "A 502 with no TLS warning is success: the certificate is real and there is"
say "simply nothing behind the proxy until the first deploy."
pause "Real certificate issued?"

confirm "Ready to finish and show the summary?"

finish

note "Production values are in .env.production, which is gitignored. Keep it."
note "Push to main and the Release workflow builds both images, publishes them"
note "to GHCR and deploys them on the runner you just registered."
