import 'package:flutter/material.dart';

import 'status_tone.dart';

/// Design tokens for the app: spacing, radius, and — as of issue #102 — a
/// three-layer colour system plus a named type scale.
///
/// The three colour layers, each built only from the one before it:
///
/// 1. **Primitive** (`_Primitives`, private to this file) — the raw hex
///    values themselves, and nothing else. A primitive is never spent
///    directly by a Screen; it exists so a value is written down exactly
///    once.
/// 2. **Semantic** ([AppColors]) — the same values named for the ROLE they
///    play (surface, border, text, action, status), never for what they
///    look like. This is the layer a Screen reaches for.
/// 3. **Component** ([AppComponentColors]) — a semantic value bound to a
///    shape that repeats across more than one widget (a selected nav
///    item's fill, a card's hairline, a focus ring), named for that shape
///    so the binding is made once rather than re-derived at each call
///    site.
///
/// **No `Color` literal and no `Colors.*` constant may appear anywhere
/// under `frontend/lib/` outside this file.** `theme_skeleton_test.dart`
/// enforces that by reading every other source file under `lib/` and
/// failing if one is found — so the rule survives the next agent rather
/// than relying on review to catch it. A Screen that needs a colour reaches
/// for [AppColors] or [AppComponentColors], or, for anything neither names,
/// for `Theme.of(context).colorScheme` directly — that is theme-derived
/// rather than literal, so it is never a violation.
///
/// Dark mode is out of scope for this pass (#99's Implementation
/// Decisions) — only the light palette ships — but nothing here is read
/// except through its semantic name, so adding a second palette later is a
/// values change to this file alone, not a Screen-by-Screen rewrite.
abstract final class Spacing {
  static const double xxs = 2;
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 16;
  static const double xl = 24;
  static const double xxl = 32;
}

/// Shared radius values.
abstract final class AppRadius {
  /// The pill used by the search field and other single-line controls.
  static const double pill = 28;

  /// The card radius the app already uses everywhere.
  static const double card = 14;
}

/// Layout tokens (issue #189): the sizes a Screen's own page agrees on,
/// written down once rather than re-picked per Screen.
///
/// This exists because six Screens were each declaring their own
/// `static const double maxWidth` — 700, 760, 760, 800, 800, 800 against the
/// 900 the Directory, Org Units, the Approval queue and Home already used — and
/// nothing said which was intended. A Screen still declares its own constant
/// (so `SkeletonList(maxWidth: X.maxWidth)` keeps working and the Screen's own
/// vocabulary stays in its file); it just does not decide the number.
///
/// **The wide pages are exceptions and name themselves as such.** The Work
/// orders table, the maintenance registers, the Action log and the tier board
/// lay out tables and boards that need more than [pageWidth]; the employee and
/// Work order detail Screens are single-record pages whose narrower measure is
/// a reading decision. Those keep their own numbers deliberately — this token
/// names the default, not a rule every Screen must spend.
abstract final class AppLayout {
  /// A Screen's page: the box its title, controls and list are laid out in,
  /// centred in whatever width the Shell leaves.
  static const double pageWidth = 900;
}

/// Layer 1 — primitives. Raw values only, and only the ones a semantic or
/// component token below actually spends.
///
/// **Where these values come from (issue #169).** The palette is the
/// `ui-ux-pro-max` design skill's own "Analytics Dashboard" scheme, adopted
/// wholesale on the user's explicit approval: primary `#1E40AF` with white on
/// it, background `#F8FAFC`, foreground `#1E3A8A`, muted `#E9EEF6` with
/// `#475569` on it, border `#DBEAFE`, destructive `#DC2626`, and a
/// primary-coloured ring. Two of its roles are deliberately not carried as
/// tokens: the skill's accent (`#D97706`, amber) is the family this Platform
/// already spends through [StatusTone.warning], and its secondary
/// (`#3B82F6`) is a second brand colour the Platform has no use for — a token
/// nothing spends is the speculative generality this layer's own rule above
/// rules out, so `secondary` is generated by the scheme and named nowhere here.
///
/// This **supersedes #102's own choice of seed**, which kept the standalone
/// dark slate the Platform was born with (`#0F172A`) and recorded its
/// `fromSeed` output as literals. #102's reasoning was that the Platform
/// absorbs two predecessor applications and should not inherit either one's
/// palette — a concern this palette does not raise, because it comes from the
/// design skill's own dashboard scheme rather than from
/// `employee-management`'s indigo. Two things #102 got right and this keeps:
/// the values are still written down exactly once, here, and the three-layer
/// structure above is untouched.
///
/// Every pair this file hands out was measured rather than estimated, and the
/// ratio is recorded beside it (a measurement, not a claim that something
/// "looks fine"): foreground 10.36:1 on a card and 9.90:1 on the canvas, muted
/// foreground 7.58:1 and 7.24:1, white on primary 8.72:1, primary on its own
/// container 8.49:1, and all five status tones between 5.3:1 and 8.5:1
/// (see [AppComponentColors.statusForeground]'s own table).
abstract final class _Primitives {
  /// The skill's `--color-primary`. 8.72:1 against white, in both directions.
  static const Color primary = Color(0xFF1E40AF);
  static const Color onPrimary = Color(0xFFFFFFFF);

  /// The selected Destination's fill and the colour on it: the skill's
  /// `--color-border` blue-100 reused as a container, with the scheme's own
  /// foreground on top (8.49:1).
  static const Color primaryContainer = Color(0xFFDBEAFE);

  /// The skill's `--color-destructive`. 4.83:1 against white — the floor for
  /// text, and exactly why the *status* red below is a shade darker: red on
  /// its own tint is not the same measurement as red on white.
  static const Color error = Color(0xFFDC2626);
  static const Color onError = Color(0xFFFFFFFF);

  /// The pale red behind anything on an error surface — a refusal banner, a
  /// shortfall badge, a status chip saying something failed. One value, spent
  /// by two roles (`colorScheme.errorContainer` and the danger status fill),
  /// named once here so the two cannot drift apart.
  static const Color errorContainer = Color(0xFFFEE2E2);
  static const Color onErrorContainer = Color(0xFF991B1B);

  /// The skill's `--color-background`: the scaffold behind every card.
  static const Color canvas = Color(0xFFF8FAFC);

  /// The skill's `--color-foreground`. 10.36:1 on a card, 9.90:1 on the
  /// canvas. A cool near-black rather than the neutral one the Platform used
  /// to carry: against a slate canvas and blue-bordered cards, a neutral
  /// black reads as a colour from a different family.
  ///
  /// Spent as the scheme's `onSurface`, as `onPrimaryContainer` over
  /// [primaryContainer], and as the label colour of an `info` status chip —
  /// the same value in three roles, which is why it is written once.
  static const Color onSurface = Color(0xFF1E3A8A);

  /// The skill's `--color-muted-foreground`. 7.58:1 on a card, 7.24:1 on the
  /// canvas.
  static const Color onSurfaceVariant = Color(0xFF475569);

  /// The skill's `--color-muted` — a quiet surface, not a colour. Spent by the
  /// table's own header band, by the skeleton placeholders, by the sidebar's
  /// avatar fill, and as the neutral status fill. Against white it is 1.17:1:
  /// a surface, never text.
  static const Color muted = Color(0xFFE9EEF6);

  /// The skill's `--color-border` — the hairline around a flattened card and
  /// under a table's header band. 1.22:1 against white: a hairline, never
  /// text.
  static const Color edge = Color(0xFFDBEAFE);

  /// The rim of an outlined control — an `OutlinedButton`, a picker's own
  /// panel, an input's border. 4.76:1 against white, which matters twice: a
  /// border below 3:1 fails WCAG 1.4.11 (non-text contrast) outright, and the
  /// near-white hairline this Platform used to derive from its seed left every
  /// outlined control reading as disabled rather than pressable. It is slate,
  /// not blue: a blue rim at this weight competes with the action colour,
  /// which is what a border is supposed to sit behind.
  static const Color outline = Color(0xFF64748B);

  /// The action colour at 10% over white (`#E8ECF7`) — the highlight that
  /// follows the pointer across a table row. A raw value like every other
  /// primitive; the role it plays is named in [AppColors.surfaceHover].
  static const Color hover = Color(0x1A1E40AF);

  /// Plain white: the panel surface, a card's own fill, and the fill of every
  /// input.
  static const Color white = Color(0xFFFFFFFF);

  /// The three status roles Material 3 does not define: success, warning and
  /// the darker red a status wears *on its own tint* (5.30:1 there, where
  /// [error] alone would measure 3.95:1). Each is the darker shade of its own
  /// family — green-800, orange-800, red-700 — chosen for the floor rather
  /// than for taste, and each measured against its own fill below.
  ///
  /// **Warning is orange, not amber** (`#9A3412`, orange-800). The first value
  /// tried was amber-800 (`#92400E`), which measures 6.37:1 and is legible —
  /// and next to the green it reads as *brown*, which nobody scans as "warn".
  /// Orange-800 measures 6.56:1 on the amber tint and 6.38:1 on the orange one
  /// below, and is unmistakably the middle of the three.
  static const Color success = Color(0xFF166534);
  static const Color warning = Color(0xFF9A3412);
  static const Color danger = Color(0xFFB91C1C);

  /// The status fills (issue #168) — one tint per [StatusTone], each measured
  /// against its own foreground below and none below 4.5:1. Two of them are
  /// values this file already keeps ([muted] and [errorContainer]) rather than
  /// second copies of the same hex: one value, named once, spent by more than
  /// one role, which is the rule layer 1 exists to keep.
  static const Color successFill = Color(0xFFDCFCE7);
  static const Color warningFill = Color(0xFFFFEDD5);
}

/// Layer 2 — semantic tokens, named for the role they play rather than
/// their appearance. This is the layer a Screen reaches for; see this
/// file's top doc comment for the full three-layer picture (issue #102).
///
/// `canvas` and `edge` keep both their names and their places; their values
/// are the skill's own `--color-background` and `--color-border` (issue
/// #169), where #102 had them as a cool off-white and a neutral hairline.
abstract final class AppColors {
  // --- surface ---

  /// The scaffold background.
  static const Color canvas = _Primitives.canvas;

  /// The panel surface raised above [canvas] — the sidebar's fill, and,
  /// via [AppComponentColors.cardBorder], every flattened card's own fill.
  /// Plain white, same as before this rewrite; only its name is new.
  static const Color card = _Primitives.white;

  // --- border ---

  /// The hairline every flattened card, panel and divider uses.
  static const Color edge = _Primitives.edge;

  // --- text ---

  /// Body and heading text.
  static const Color textPrimary = _Primitives.onSurface;

  /// Secondary text — metadata, captions, anything a Screen wants read as
  /// quieter than [textPrimary] without dropping below the 4.5:1 floor.
  static const Color textMuted = _Primitives.onSurfaceVariant;

  // --- surface ---

  /// A quiet surface rather than a colour: the table's own column-label band,
  /// and anything that wants to read as recessed next to [card]. 1.17:1
  /// against white, which is what makes it a surface and never text.
  static const Color surfaceMuted = _Primitives.muted;

  /// The highlight that follows the pointer across a row (the action colour at
  /// 10% over white). Named here rather than left as a literal inside
  /// [AppComponentColors.rowHoverFill], so that the component layer binds a
  /// semantic value the way this file's own layer rule says it does.
  static const Color surfaceHover = _Primitives.hover;

  // --- action ---

  /// The Platform's one action colour — buttons, links, and the selected
  /// nav item's foreground (see [AppComponentColors.navSelectedForeground]).
  static const Color actionPrimary = _Primitives.primary;

  /// Text or an icon drawn on top of an [actionPrimary] fill.
  static const Color onActionPrimary = _Primitives.onPrimary;

  // --- status ---

  /// An error, or a destructive action — but the *darker* red (5.3:1), not
  /// the theme's own `colorScheme.error` (`#DC2626`, 4.83:1 on white). The two
  /// are the same family and different jobs: `#DC2626` is red on white, which
  /// is what a destructive button and a form error need; this is red on its
  /// own pale tint, where `#DC2626` measures 3.95:1 and would fail the floor.
  /// A Screen reaches for this one whenever the red is a status rather than a
  /// call to action.
  static const Color statusDanger = _Primitives.danger;

  /// Success. Material 3 has no role for this, so #102 adds one. The value is
  /// the skill palette's green family at the shade that measures against its
  /// own tint rather than against white — 6.49:1, where green-600 (`#16A34A`)
  /// measures 3.0:1 and would be a status nobody with ordinary sight could
  /// read on a chip.
  static const Color statusSuccess = _Primitives.success;

  /// Warning. Likewise absent from Material 3, and **orange rather than
  /// amber**: the skill's accent (`#D97706`) is this family's mid-tone and
  /// measures 2.86:1 on the tint — a highlight, never a text colour — and
  /// amber-800 measures 6.37:1 but reads as brown beside the green. This is
  /// orange-800 at 6.38:1 on the orange tint, which is the middle of the three
  /// the moment a reader looks at a list.
  static const Color statusWarning = _Primitives.warning;

  // --- status fills ---
  //
  // The fills half of the same five bindings, named here rather than reached
  // for as primitives by [AppComponentColors.statusFill] — the layer this file
  // declares says a component token binds a *semantic* value, and a component
  // reaching past this layer into `_Primitives` would be the one shortcut in
  // the file that makes the layering a story rather than a rule.
  //
  // Two of them name a value another role already owns ([surfaceMuted] and the
  // scheme's own `errorContainer`): one value, two roles, written once.

  /// The quiet fill: a settled state, a deliberate cancellation, a retirement.
  static const Color statusNeutralFill = _Primitives.muted;

  /// The live fill — the same value as
  /// [AppComponentColors.navSelectedBackground] (the skill's border blue used
  /// as a container), because an actionable status and the selected
  /// Destination say the same thing.
  static const Color statusInfoFill = _Primitives.primaryContainer;

  /// The finished fill.
  static const Color statusSuccessFill = _Primitives.successFill;

  /// The fill that wants a decision.
  static const Color statusWarningFill = _Primitives.warningFill;

  /// The fill for a fault — a step that failed.
  static const Color statusDangerFill = _Primitives.errorContainer;

  /// The text on [statusInfoFill] — the scheme's own foreground, which is what
  /// `onPrimaryContainer` resolves to as well: 8.49:1 on that fill.
  static const Color statusInfoForeground = _Primitives.onSurface;
}

/// Layer 3 — component tokens: a semantic value bound to a shape that
/// repeats across more than one widget, named for that shape so the
/// binding is made once rather than re-derived at each call site (issue
/// #102).
abstract final class AppComponentColors {
  /// The selected sidebar destination's fill (`_NavItem` in
  /// `platform/shell.dart`).
  static const Color navSelectedBackground = _Primitives.primaryContainer;

  /// The selected sidebar destination's icon and label, paired with
  /// [navSelectedBackground].
  static const Color navSelectedForeground = AppColors.actionPrimary;

  /// The hairline drawn around a flattened card, and around the inline
  /// panels that echo one — the `Border.all` a handful of dialogs draw by
  /// hand around a nested picker or list (e.g. `people/org_unit_picker.dart`,
  /// `maintenance/org_unit_chooser.dart`).
  static const Color cardBorder = AppColors.edge;

  /// The ring a focused control is drawn with. Named here so the
  /// keyboard-focus work #99's Implementation Decisions still owes (its
  /// user story 21) has a token to reach for rather than a reason to invent
  /// a colour; [buildAppTheme]'s own `focusColor` already spends it.
  static const Color focusRing = AppColors.actionPrimary;

  /// The mark drawn beside the selected Destination in the Shell (issue #168).
  ///
  /// The selected Destination already differed by fill
  /// ([navSelectedBackground]), by foreground ([navSelectedForeground]) and by
  /// label weight — but a pale tint against near-white is precisely the cue a
  /// low-vision reader or a badly calibrated display loses first, and a weight
  /// step on 14px text is a faint one. This is the cue that survives both,
  /// and it is the same action colour the selected label is already set in,
  /// so nothing new is being introduced into the palette.
  static const Color navSelectedAccent = AppColors.actionPrimary;

  /// The band behind a table's column labels (issue #168).
  ///
  /// The wide Work orders table's header row used to sit on the same white as
  /// its data, separated by one hairline — so it read as a fifth row rather
  /// than as a header.
  ///
  /// The first band value shipped was `#F7F7FB`, and that was wrong, caught by
  /// looking at the regenerated golden rather than by any test: against a white
  /// row it measures 1.02:1, a band nobody can see, so the header still read as
  /// a data row. It is the palette's own muted `#E9EEF6` (1.17:1) — still
  /// quiet, but visibly a band. The value is shared with
  /// [StatusTone.neutral] deliberately: "quiet fill" means the same thing in
  /// both places, and two nearly identical greys would be two things to keep in
  /// step for no gain.
  static const Color tableHeaderFill = AppColors.surfaceMuted;

  /// The highlight under the pointer as it tracks across a table row
  /// (issue #168).
  ///
  /// A row here is seven columns wide and is itself tappable (`_WorkOrderTableRow`'s
  /// own `InkWell`, which opens the Work order), so the pointer's own position
  /// is the only thing tying an ID at the left edge to an action at the right.
  /// Material's default hover highlight is deliberately faint and, on a white
  /// row beside six other white rows, effectively invisible — this is the
  /// action colour at 10% over white (`#E8ECF7`), which is legible as a band
  /// without becoming a selection state. Body text on it measures 8.77:1 and
  /// muted metadata 6.41:1, so the highlight never costs anybody readability.
  static const Color rowHoverFill = AppColors.surfaceHover;

  /// The fill a status chip wears for [tone] (issue #168).
  ///
  /// A switch rather than a map so that adding a [StatusTone] is a compile
  /// error here until it is given a fill — the same reason [StatusTone] keeps
  /// the five meanings in one place. `widgets/status_chip.dart` is the only
  /// spender today; every Screen that shows a status goes through that widget
  /// rather than reaching for this method directly.
  static Color statusFill(StatusTone tone) => switch (tone) {
        StatusTone.neutral => AppColors.statusNeutralFill,
        StatusTone.info => AppColors.statusInfoFill,
        StatusTone.success => AppColors.statusSuccessFill,
        StatusTone.warning => AppColors.statusWarningFill,
        StatusTone.danger => AppColors.statusDangerFill,
      };

  /// The text (and icon) colour paired with [statusFill], per [tone] — the
  /// other half of the same binding. Every pair is measured, none is below the
  /// 4.5:1 floor, and `status_chip_test.dart` measures them again rather than
  /// trusting this table:
  ///
  /// | tone | against its own fill |
  /// |------|----------------------|
  /// | neutral | 6.50:1 |
  /// | info | 8.49:1 |
  /// | success | 6.49:1 |
  /// | warning | 6.38:1 |
  /// | danger | 5.30:1 |
  ///
  /// The three status roles are [AppColors]' own semantic values rather than
  /// new ones, so a status colour is written down exactly once in this file.
  static Color statusForeground(StatusTone tone) => switch (tone) {
        StatusTone.neutral => AppColors.textMuted,
        StatusTone.info => AppColors.statusInfoForeground,
        StatusTone.success => AppColors.statusSuccess,
        StatusTone.warning => AppColors.statusWarning,
        StatusTone.danger => AppColors.statusDanger,
      };
}

/// The Platform's type scale (issue #102). Material 3's own scale already
/// supplies the exact numbers wanted, so this class names which role a
/// Screen should reach for rather than redefining any of them —
/// `ThemeData.textTheme`, built by [buildAppTheme] from the Material 3
/// defaults and tinted by the seed's `ColorScheme`, stays the source of
/// truth.
///
/// - **Body** — `bodyLarge`, 16px / 24px line height (1.5). The base size
///   this ticket asks for; new body copy should reach for this.
/// - **Dense** — `bodyMedium`, 14px / 20px. Still correct for labels,
///   metadata and dense table cells; not being replaced.
/// - **Floor** — `bodySmall`, 12px / 16px. Nothing in the Platform goes
///   below this. **Enforced as of issue #168**: the last labels that sat below
///   it — including the Shell's own Destination-group heading, at 11px — were
///   brought up to `labelMedium`, and `labelSmall` is no longer spent anywhere
///   under `lib/`. A new label below this floor is a regression, not a
///   judgement call.
///
/// The existing Screens still reach for `bodyMedium` as their body
/// default — migrating all of them is deliberately out of scope for #102
/// (see #99's Implementation Decisions on scope, and its note that
/// restyling a client about to be restructured means restyling it twice).
/// `home_screen.dart` is updated to [body] here only because #102 is
/// already touching that file for its colour fix.
abstract final class AppTypography {
  static TextStyle? body(BuildContext context) => Theme.of(context).textTheme.bodyLarge;

  static TextStyle? dense(BuildContext context) => Theme.of(context).textTheme.bodyMedium;

  static TextStyle? floor(BuildContext context) => Theme.of(context).textTheme.bodySmall;
}

/// Builds the app theme.
///
/// The palette is the `ui-ux-pro-max` design skill's own "Analytics Dashboard"
/// scheme (issue #169), approved by the user: blue data, amber warnings, red
/// failures. `colorScheme` is built from that palette and pinned role by role
/// rather than left to `fromSeed` alone — the scheme's own algorithm picks
/// *companion* tones for the roles this file does not name, but every role the
/// Platform reads is the value written down in [_Primitives], so a Flutter
/// upgrade cannot quietly restyle the app.
///
/// This **replaces #102's seed** (`#0F172A`, the dark slate the Platform was
/// born with). #102's own reasoning — that the Platform absorbs two
/// predecessor applications and should read as neither — still holds, and this
/// palette does not raise it: it is the design skill's own dashboard scheme,
/// not a predecessor's colours.
///
/// #102's other decision is untouched: every colour here is a named token from
/// [AppColors] or [AppComponentColors], never a literal at a call site, and
/// the flattened cards, filled inputs and flattened elevation below are
/// unchanged.
ThemeData buildAppTheme() {
  // A focused control's own visible ring (#99 user story 21, #104's own
  // accessibility criteria): `focusColor` above feeds `InkWell`/`Focus`
  // directly, but a Material 3 `ButtonStyleButton` (`OutlinedButton`,
  // `FilledButton`, `IconButton`) resolves its *own* default overlay for
  // `WidgetState.focused` rather than reading `ThemeData.focusColor` — so
  // without this, a focused button would still show Material's own subtle
  // default rather than this app's own [AppComponentColors.focusRing].
  // Wired once here, at the theme, rather than per button style at each
  // call site, so every current and future button gets the same ring for
  // free — `work_orders_test.dart`'s own focus test reads these two
  // `ButtonStyle`s back off a pumped `Theme.of(context)` to prove it.
  final focusedOverlay = WidgetStateProperty.resolveWith<Color?>(
    (states) => states.contains(WidgetState.focused)
        ? AppComponentColors.focusRing.withValues(alpha: 0.16)
        : null,
  );
  final focusedSide = WidgetStateProperty.resolveWith<BorderSide?>(
    (states) => states.contains(WidgetState.focused)
        ? const BorderSide(color: AppComponentColors.focusRing, width: 2)
        : null,
  );

  // The palette, pinned role by role (issue #169). `fromSeed` still picks the
  // *companion* tones for the roles this file does not name — the inverse
  // roles, the tertiary family, the surface tints nothing here reads — but
  // every role the Platform actually renders is the value written down in
  // `_Primitives`, so `fromSeed`'s algorithm (which #102 already noted is not
  // guaranteed stable across Flutter releases) cannot quietly restyle the app
  // on the next upgrade.
  final scheme = ColorScheme.fromSeed(seedColor: _Primitives.primary).copyWith(
    primary: _Primitives.primary,
    onPrimary: _Primitives.onPrimary,
    primaryContainer: _Primitives.primaryContainer,
    // The same value the scheme's own `onSurface` gets, in a second role.
    onPrimaryContainer: _Primitives.onSurface,
    error: _Primitives.error,
    onError: _Primitives.onError,
    errorContainer: _Primitives.errorContainer,
    onErrorContainer: _Primitives.onErrorContainer,
    surface: _Primitives.white,
    onSurface: _Primitives.onSurface,
    onSurfaceVariant: _Primitives.onSurfaceVariant,
    // The hairline. Every table row, card and panel reaches for this through
    // `outlineVariant` (`_WorkOrderTableRow`'s own bottom border), so it is
    // the palette's border rather than a generated one.
    outlineVariant: _Primitives.edge,
    // The rim of an outlined control, which is a different job from the
    // hairline above and needs a different weight to do it: 4.76:1 rather than
    // 1.22:1, so an OutlinedButton or an input reads as something you can
    // press. Left to `fromSeed`, this came out a neutral grey at roughly 1.6:1
    // and every outlined control read as disabled.
    outline: _Primitives.outline,
    // Read by the skeleton placeholders and the sidebar's own avatar fill.
    surfaceContainerHighest: _Primitives.muted,
    // A deliberate binding to what this client actually paints with the role
    // (issue #169): every write confirmation in the Platform — "Work order
    // raised", "Employee corrected" — is a notice banner wearing
    // `secondaryContainer` with `onSecondaryContainer` on it, and failures wear
    // `errorContainer` beside them. So the "something worked" surface is the
    // success pair, and a confirmation reads green the way the green status
    // does rather than as a second, unexplained lavender.
    //
    // This is a statement about this client's use of the role, not a claim
    // about Material's secondary semantics: a future Screen that wants a real
    // secondary colour needs its own token rather than this one.
    secondaryContainer: _Primitives.successFill,
    onSecondaryContainer: _Primitives.success,
  );

  return ThemeData(
    useMaterial3: true,
    colorScheme: scheme,
    fontFamily: 'Roboto',
    scaffoldBackgroundColor: AppColors.canvas,
    focusColor: AppComponentColors.focusRing.withValues(alpha: 0.12),
    cardTheme: CardThemeData(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppRadius.card),
        side: const BorderSide(color: AppComponentColors.cardBorder),
      ),
    ),
    inputDecorationTheme: const InputDecorationTheme(
      filled: true,
      fillColor: AppColors.card,
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: ButtonStyle(overlayColor: focusedOverlay, side: focusedSide),
    ),
    filledButtonTheme: FilledButtonThemeData(
      style: ButtonStyle(overlayColor: focusedOverlay),
    ),
    iconButtonTheme: IconButtonThemeData(
      style: ButtonStyle(overlayColor: focusedOverlay, side: focusedSide),
    ),
  );
}
